Capstone project
yersel500/capstone-project-yh pull request #1
Opened 2022-02-02 19:50 UTC by yersel500

I develop a website related to "Crypto Congress" with the next features:

- Actually, the webpage has two pages: Home and About pages.
- The speaker section was created dynamically with javascript.
- The mobile version has a hamburger menu for better navigation.

To build the project, I use:

- HTML
- CSS
- Javascript.

2022-02-02 21:24 UTC, Rustamxon7 requested changes
Hi @yersel500  , 

Good job so far!

### HIGHLIGHTS!

- No linters errors.💯
- Dry code 💯
- Design is beautiful ✔


There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 21:24 UTC, Rustamxon7 commented on README.md
> +[Video of the project](https://www.loom.com/share/38c974bd76f948f693195491251ac9de)
## GOOD JOB SO FAR 🙌
- [ ] [OPTIONAL] Your presentation is awesome and also helped me review your code better 😀. Keep on creating these kinds of great projects 🥇

2022-02-02 21:24 UTC, Rustamxon7 commented on about.html
> +  </nav>
- [ ] As a requirement you should personalize the content by following the design ⚠. There is no top black part of the navigation on your website. Let's add to fix this issue 😉. And also don't forget to hide it on the mobile version.

#### Original design
![image](https://user-images.githubusercontent.com/69011963/152238694-21b35f4c-84d2-43b3-8c1a-a77ae5474129.png)

#### Your website missing part
![image](https://user-images.githubusercontent.com/69011963/152238856-07cd5eb0-d548-4bdf-ac24-5ecadc02ae4a.png)

2022-02-02 21:24 UTC, Rustamxon7 commented on index.html
> +
- [ ] [OPTIONAL] There is one little thing I realized is in this button. Please also change the text `MORE` to `LESS` when it opened 🙌

#### Screenshot 
![image](https://user-images.githubusercontent.com/69011963/152239498-46c37803-bd56-44ae-a73f-d9aecbad9ca8.png)

2022-02-03 00:59 UTC, Hamzaoutdoors approved these changes
Hey @yersel500, I am **Hamza** your reviewer for this PR 😸 

## Congratulotions, Project Approved 🟢 

_You did a great job Yersel, I really enjoyed surfing on your website 😃_ 

## To Highlight
✔️ The repo looks professional
✔️ Git/GitHub flow best practices have been followed
✔️ There are no linter errors
✔️ You have a descriptive README
✔️ Wonderful UI design and good choice of theme🥇 
✔️ Great Job building your project with **Mobile-First**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 11:31 UTC, merged